<div class="sol"></div>
<div class="mar"></div>
<div class="cube">
<div class="face face--front">
    <form action="/cadastrar" method="POST" class="login">
        <h2 class="h2 p-3">Cadastre-se</h2>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
            </div>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="nome curto">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Email</span>
            </div>
            <input type="text" class="form-control" id="email" name="email" placeholder="seu melhor">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Senha</span>
            </div>
            <input type="password" class="form-control" id="senha" name="senha" placeholder="**********">
        </div>
        <button type="submit" class="btn">Cadastrar</button><br>
        <a href='/' class="btn">Voltar</a>
        <p>&copy; 2022-2023</p>
    </form>
</div>
<div class="face face--right"></div>
<div class="face face--back"></div>
<div class="face face--left"></div>
<div class="face face--top"></div>
<div class="face face--bottom"></div>